### ISSUE TITLE
음 nodeschool seoul 이 현재 활동이 어떻게 되나요?

### ISSUE THREAD

**Issue by hoony-o-1** [nodeschool/seoul#8]
gitter에서 얘기를 해보니 아무도 팔로업을 안하고 계시는 것 같아서요 ㅜ

한국에서는 한번도 워크샵을 안했던 것 같은데, 워크샵을 기획하시다가 현재 번역에 집중하고 계신건지

이런 저런 상황이 궁금하네요 ^^

**Comment by taggon** [comment]
일단 번역 외에는 별다른 활동이 없는 상태입니다. ㅠ_ㅠ
번역도 거의 @marocchino 님이 전담하고 계시네요...

**Comment by hoony-o-1** [comment]
아 답변 감사합니다! :+1:
