### ISSUE TITLE
서울워크숍을 개최하는데 관심있는 분들 계실까요?(code.org 행사 겸 열면 어떨까요?)

### ISSUE THREAD

**Issue by hoony-o-1** [nodeschool/seoul#9]
일단 제 소개부터 드리면 코드포서울 커뮤니티에서 주로 활동하고 있는 장승훈이라고 합니다. 오픈 관련된 전반적인 이슈들에 관심이 많구요 ^^

작년에 씨씨코리아에 개발자로 일하고 계시는 홍영택님과 code.org 행사를 작게 열어보려다 무산되었던 기억이 있습니다. 원래 자바스크립트에 관심이 많아서 nodeschool 도 알고는 있었는데 딱히 학습에 사용해본 적은 없는데 이렇게 seoul 챕터에 활동하는 분들이 계신 줄 몰랐네요 ^^

오픈 관련된 이슈에 관심이 많기도 하고 저 역시 독학으로 프로그래밍을 공부해오고 있는 와중이라 이렇게 자발적으로 만들어진 자료로 쉽게 개발을 시작하고자 하는 분들에게 도움이 되었으면 하는 마음이 있습니다. 그래서 올해에도 12월에 code.org 행사, the hour of code가 전 세계에서 열리는데 nodeschool 서울 첫 워크숍으로 겸해서 열리면 좋겠다라는 생각이 들더라구요. 기존에 꾸준히 번역을 해오셨던 분들이 계시기 때문에 그 중 워크숍에 관심이 있는 분들이 계시면 저도 도움이 되어서 같이 열어보면 어떨까 합니다.

gitter 에는 @marocchino 님 밖에 안계셔서 일단 이슈에 남겼어요! 혹시 더 이야기를 나누고자 하는 분들은 같이 gitter에 들어오셔서 의견을 나눠보면 좋을 것 같습니다.  :octocat:

**Comment by taggon** [comment]
code.org도 행사가 열리는군요. 초기에 번역자 모을 때 참여해서 동영상 몇 개를 번역한 적이 있어서 반갑네요.
저도 행사를 여는 것은 좋다고 생각하지만, 지금부터 준비하기엔 조금 빠듯하지 않을까 걱정입니다.

**Comment by hoony-o-1** [comment]
아 12월까지 준비하기엔 시간이 좀 빠듯하려나요 ㅜ? 말그대로 워크숍이니만큼 10~20명 정도의 가벼운 행사로 생각하고 준비하면 괜찮지 않을까 생각했는데 그럴 수도 있겠네요. @taggon 님도 관심있으시면 gitter에 와서 의견 같이 나누는 것은 어떠신가요!?
